# Generated by Django 4.1.7 on 2023-03-05 05:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('Photo', models.ImageField(blank=True, default='NULL', null=True, upload_to='images')),
                ('Created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
