# Generated by Django 4.1.7 on 2023-03-05 08:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_info_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='Category',
            field=models.CharField(choices=[('Certificate', 'Certificate'), ('Cat', 'Cat')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
