# Generated by Django 4.1.2 on 2022-10-19 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donermodel',
            name='maritalstatus',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married')], default='unmarried', max_length=20),
        ),
    ]
